.PHONY: install install-vim

install: install-vim


#
# Vim
#
install-vim: $(USERPROFILE)\_vimrc

$(USERPROFILE)\_vimrc: $(USERPROFILE)\vimfiles\autoload\plug.vim vimrc
	copy vimrc $@
	vim +PlugInstall +qall

$(USERPROFILE)\vimfiles\autoload\plug.vim:
	mkdir $(dir $@)
	powershell -command "(new-object System.Net.WebClient).DownloadFile('https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', '$@')"

